CREATE TABLE TA_ACHIEVEMENTS (
    ID_ACHIEVEMENT BIGINT NOT NULL AUTO_INCREMENT,
    ACHIEVEMENT_DOWN BOOLEAN NOT NULL,
    ACHIEVEMENT_DOWN_DATE TIMESTAMP NOT NULL,
    ID_BOSS BIGINT,
    ID_DIFFICULTY INTEGER,
    PRIMARY KEY (ID_ACHIEVEMENT)
);
CREATE TABLE TA_ARTICLES (
    ARTICLE_TYPE VARCHAR(31) NOT NULL,
    ID_ARTICLE BIGINT NOT NULL AUTO_INCREMENT,
    ARTICLE_CONTENT TEXT(255) NOT NULL,
    ARTICLE_CREATION_DATE TIMESTAMP NOT NULL,
    ARTICLE_UPDATE_DATE TIMESTAMP NOT NULL,
    ARTICLE_HEADER_IMAGE VARCHAR(255) NOT NULL,
    ARTICLE_ILLUSTRATION VARCHAR(255) NOT NULL,
    ARTICLE_PREVIEW VARCHAR(255) NOT NULL,
    ARTICLE_TITLE VARCHAR(150) NOT NULL,
    NEWS_COVERAGE_IMAGE VARCHAR(255),
    ID_USER BIGINT,
    PRIMARY KEY (ID_ARTICLE)
);
CREATE TABLE TA_ARTICLES_GROUPS (
    TA_ARTICLES_ID_ARTICLE BIGINT NOT NULL,
    TA_GROUPS_ID_GROUP INTEGER NOT NULL
);
CREATE TABLE TA_BOSSES (
    ID_BOSS BIGINT NOT NULL AUTO_INCREMENT,
    BOSS_ILLUSTRATION VARCHAR(255) NOT NULL,
    BOSS_NAME VARCHAR(50) NOT NULL,
    BOSS_ORDER INTEGER NOT NULL,
    PRIMARY KEY (ID_BOSS)
);
CREATE TABLE TA_CHARACTERS (
    ID_CHARACTER BIGINT NOT NULL AUTO_INCREMENT,
    ID_CLASS INTEGER,
    ID_FACTION INTEGER,
    ID_SPECIALISATION BIGINT,
    ID_USER BIGINT,
    ID_RACE INTEGER,
    ID_REALM INTEGER,
    ID_SPECIALIZATION BIGINT,
    PRIMARY KEY (ID_CHARACTER)
);
CREATE TABLE TA_CLASSES (
    ID_CLASS INTEGER NOT NULL AUTO_INCREMENT,
    CLASS_IMAGE VARCHAR(255) NOT NULL,
    CLASS_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_CLASS)
);
CREATE TABLE TA_DIFFICULTIES (
    ID_DIFFICULTY INTEGER NOT NULL AUTO_INCREMENT,
    DIFFICULTY_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_DIFFICULTY)
);
CREATE TABLE TA_EXTENSIONS (
    ID_EXTENSION BIGINT NOT NULL AUTO_INCREMENT,
    EXTENSION_LOGO VARCHAR(255) NOT NULL,
    EXTENSION_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_EXTENSION)
);
CREATE TABLE TA_FACTIONS (
    FACTION_TYPE VARCHAR(31) NOT NULL,
    ID_FACTION INTEGER NOT NULL AUTO_INCREMENT,
    FACTION_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_FACTION)
);
CREATE TABLE TA_FORUMS (
    ID_FORUM BIGINT NOT NULL AUTO_INCREMENT,
    FORUM_DESCRIPTION VARCHAR(255),
    FORUM_NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID_FORUM)
);
CREATE TABLE TA_FORUMS_CATEGORIES (
    ID_FORUM_CATEGORY BIGINT NOT NULL AUTO_INCREMENT,
    FORUM_CATEGORY_DESCRIPTION VARCHAR(255),
    FORUM_CATEGORY_NAME VARCHAR(100) NOT NULL,
    ID_FORUM BIGINT,
    PRIMARY KEY (ID_FORUM_CATEGORY)
);
CREATE TABLE TA_FORUMS_GROUPS (
    TA_FORUMS_ID_FORUM BIGINT NOT NULL,
    TA_GROUPS_ID_GROUP INTEGER NOT NULL
);
CREATE TABLE TA_FORUMS_POSTS (
    ID_FORUM_POST BIGINT NOT NULL AUTO_INCREMENT,
    FORUM_POST_CONTENT TEXT(255) NOT NULL,
    FORUM_POST_CREATION_DATE TIMESTAMP NOT NULL,
    FORUM_POST_UPDATE_DATE TIMESTAMP NOT NULL,
    FORUM_POST_LOCKED BOOLEAN NOT NULL,
    FORUM_POST_TITLE VARCHAR(150) NOT NULL,
    ID_USER BIGINT,
    ID_FORUM_CATEGORY BIGINT,
    PRIMARY KEY (ID_FORUM_POST)
);
CREATE TABLE TA_FORUM_REPLY (
    ID_FORUM_REPLY BIGINT NOT NULL AUTO_INCREMENT,
    FORUM_REPLY_CONTENT TEXT(255) NOT NULL,
    FORUM_REPLY_CREATION_DATE TIMESTAMP NOT NULL,
    FORUM_REPLY_UPDATE_DATE TIMESTAMP,
    ID_USER BIGINT,
    ID_FORUM_POST BIGINT,
    PRIMARY KEY (ID_FORUM_REPLY)
);
CREATE TABLE TA_GROUPS (
    ID_GROUP INTEGER NOT NULL AUTO_INCREMENT,
    GROUP_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_GROUP)
);
CREATE TABLE TA_PATCHES (
    ID_PATCH BIGINT NOT NULL AUTO_INCREMENT,
    PATCH_NAME VARCHAR(100) NOT NULL,
    PATCH_VERSION_X VARCHAR(2) NOT NULL,
    PATCH_VERSION_Y VARCHAR(2) NOT NULL,
    PATCH_VERSION_Z VARCHAR(2) NOT NULL,
    ID_EXTENSION BIGINT,
    PRIMARY KEY (ID_PATCH)
);
CREATE TABLE TA_RACES (
    ID_RACE INTEGER NOT NULL AUTO_INCREMENT,
    RACE_NAME VARCHAR(50) NOT NULL,
    ID_FACTION INTEGER,
    PRIMARY KEY (ID_RACE)
);
CREATE TABLE TA_RACES_CLASSES (
    TA_RACES_ID_RACE INTEGER NOT NULL,
    TA_CLASSES_ID_CLASS INTEGER NOT NULL
);
CREATE TABLE TA_RAIDS (
    ID_RAID BIGINT NOT NULL AUTO_INCREMENT,
    RAID_ACRONYM VARCHAR(6),
    RAID_ILLUSTRATION VARCHAR(255) NOT NULL,
    RAID_NAME VARCHAR(100) NOT NULL,
    ID_PATCH BIGINT,
    PRIMARY KEY (ID_RAID)
);
CREATE TABLE TA_REALMS (
    ID_REALM INTEGER NOT NULL AUTO_INCREMENT,
    REALM_NAME VARCHAR(50) NOT NULL,
    ID_REGION INTEGER,
    PRIMARY KEY (ID_REALM)
);
CREATE TABLE TA_REGIONS (
    ID_REGION INTEGER NOT NULL AUTO_INCREMENT,
    REGION_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_REGION)
);
CREATE TABLE TA_RESOURCES (
    ID_RESOURCE BIGINT NOT NULL AUTO_INCREMENT,
    RESOURCE_APPEARANCE_ORDER INTEGER NOT NULL,
    RESOURCE_NAME VARCHAR(50) NOT NULL,
    RESOURCE_URI VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_RESOURCE)
);
CREATE TABLE TA_RESOURCES_GROUPS (
    TA_RESOURCES_ID_RESOURCE BIGINT NOT NULL,
    TA_GROUPS_ID_GROUP INTEGER NOT NULL
);
CREATE TABLE TA_ROLES (
    ID_ROLE BIGINT NOT NULL AUTO_INCREMENT,
    ROLE_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_ROLE)
);
CREATE TABLE TA_SPECIALIZATIONS (
    ID_SPECIALIZATION BIGINT NOT NULL AUTO_INCREMENT,
    SPECIALIZATION_IMAGE VARCHAR(255) NOT NULL,
    SPECIALIZATION_NAME VARCHAR(50) NOT NULL,
    SPECIALIZATION_RECRUITING BOOLEAN,
    ID_CLASS INTEGER,
    ID_ROLE BIGINT,
    PRIMARY KEY (ID_SPECIALIZATION)
);
CREATE TABLE TA_USERS (
    USER_TYPE VARCHAR(31) NOT NULL,
    ID_USER BIGINT NOT NULL AUTO_INCREMENT,
    USER_ACTIVE BOOLEAN NOT NULL,
    USER_AGREE_LEGALS BOOLEAN NOT NULL,
    USER_AVATAR VARCHAR(255),
    USER_BIRTH DATE,
    USER_EMAIL VARCHAR(100) NOT NULL,
    USER_NAME VARCHAR(50),
    USER_PASSWORD VARCHAR(255) NOT NULL,
    USER_PHONE_NUMBER INTEGER,
    USER_SURNAME VARCHAR(50),
    PLAYER_NICKNAME VARCHAR(50) NOT NULL,
    ID_GROUP INTEGER,
    PRIMARY KEY (ID_USER)
);
CREATE TABLE TA_VIDEOS (
    ID_VIDEO BIGINT NOT NULL AUTO_INCREMENT,
    VIDEO_DESCRIPTION VARCHAR(255) NOT NULL,
    VIDEO_INTEGRATION_CODE TEXT(255) NOT NULL,
    VIDEO_TITLE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_VIDEO)
);
