-- GUEST GROUP
INSERT INTO TA_GROUPS(GROUP_NAME) VALUES('GUEST');
-- GUEST USER
INSERT INTO TA_USERS(USER_NAME, USER_SURNAME, USER_EMAIL, USER_PASSWORD, USER_BIRTH, USER_PHONE_NUMBER, USER_ACTIVE, USER_AGREE_LEGALS, USER_AVATAR, USER_TYPE, PLAYER_NICKNAME, ID_GROUP) VALUES('playerNameReadTest', 'playerameReadTest', 'playerEmailReadTest', 'playerPasswordReadTest', DATE '1988-11-13', 0123456789, TRUE, TRUE, 'playerAvatarReadTest', 'PLAYER', 'playerNicknameReadTest', 1);
-- MAIN MENU RESOURCE
INSERT INTO TA_RESOURCES(RESOURCE_APPEARANCE_ORDER, RESOURCE_NAME, RESOURCE_URI) VALUES(1, '', '');
-- GUEST ACCESS TO MAIN MENU RESOURCE
INSERT INTO TA_RESOURCES_GROUPS(TA_RESOURCES_ID_RESOURCE, TA_GROUPS_ID_GROUP) VALUES(1,1);
-- NEWS
INSERT INTO TA_ARTICLES(ARTICLE_TITLE, ARTICLE_PREVIEW, ARTICLE_CONTENT, ARTICLE_ILLUSTRATION, ARTICLE_HEADER_IMAGE, ARTICLE_CREATION_DATE, ARTICLE_UPDATE_DATE, NEWS_COVERAGE_IMAGE, ID_USER, ARTICLE_TYPE) VALUES('articleTitle', 'articlePreview', 'articleContent', 'articleIllustration', 'articleHeaderImage', DATE '2015-05-05', DATE '2015-05-05', 'newsCoverageImage', 1, 'NEWS');